version: '3.0'
services:
  client:
    build: ./client
    container_name: client
    ports:
      - '3000:3000'
    volumes:
      - './client:/home/client_node/app'
      - '/home/client_node/app/node_modules'
    networks:
      - client-to-server
  server:
    build: ./server
    container_name: server
    ports:
      - '3001:3001'
    volumes:
      - './server:/home/server_node/app'
      - '/home/server_node/app/node_modules'
    links:
      - mongo
    networks:
      - client-to-server
      - server-to-db
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
    - ./mongo:/data/db
    networks:
      - server-to-db
networks:
  client-to-server:
    driver: bridge
  server-to-db:
    driver: bridge