version: '3.0'
services:
  client:
    build: ./client
    container_name: client
    ports:
      - '3000:3000'
    volumes:
      - './client:/home/client_node/app'
      - '/home/client_node/app/node_modules'
  server:
    build: ./server
    container_name: server
    ports:
      - '3001:3001'
    volumes:
      - './server:/home/server_node/app'
      - '/home/server_node/app/node_modules'