version: '3.0'
services:
  client:
    build: ./client
    container_name: client
    ports:
      - '3000:3000'
    volumes:
      - './client:/home/client_node/app'
      - '/home/client_node/app/node_modules'
    networks:
      - client-to-server
    env_file:
      - .env
  server:
    build: ./server
    container_name: server
    ports:
      - '3001:3001'
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - './server:/home/server_node/app'
      - '/home/server_node/app/node_modules'
    networks:
      - client-to-server
      - server-to-db
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
    - mongo:/data/db
    - ./server/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - server-to-db

networks:
  client-to-server:
    driver: bridge
  server-to-db:
    driver: bridge
volumes:
  mongo: